import os
from fpdf import FPDF
from typing import Dict, Any, List

class JanMitraPDFReport(FPDF):
    def __init__(self, use_nirmala: bool = False, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.use_nirmala = use_nirmala
        if self.use_nirmala:
            self.add_font("Nirmala", style="", fname=r"C:\Windows\Fonts\Nirmala.ttf")
            self.add_font("Nirmala", style="B", fname=r"C:\Windows\Fonts\NirmalaB.ttf")

    def header(self):
        # Header layout
        self.set_fill_color(15, 118, 110) # Primary Color #0F766E
        self.rect(0, 0, 210, 30, 'F')
        
        self.set_text_color(255, 255, 255)
        font_family = "Nirmala" if self.use_nirmala else "Helvetica"
        self.set_font(font_family, 'B', 16)
        header_text = 'जनमित्र एआई - पात्रता रिपोर्ट' if self.use_nirmala else 'JANMITRA AI - ELIGIBILITY REPORT'
        self.cell(0, 10, header_text, 0, 1, 'C')
        
        self.set_font(font_family, 'I' if not self.use_nirmala else '', 10)
        sub_text = 'आपका बुद्धिमान सरकारी कल्याण पात्रता मार्गदर्शक' if self.use_nirmala else 'Your Intelligent Government Welfare Eligibility Guide'
        self.cell(0, 5, sub_text, 0, 1, 'C')
        self.ln(10)

    def footer(self):
        # Position at 1.5 cm from bottom
        self.set_y(-15)
        font_family = "Nirmala" if self.use_nirmala else "Helvetica"
        self.set_font(font_family, 'I' if not self.use_nirmala else '', 8)
        self.set_text_color(128, 128, 128)
        footer_text = f'पृष्ठ {self.page_no()} | जनमित्र एआई पात्रता सहायक द्वारा जनरेट किया गया' if self.use_nirmala else f'Page {self.page_no()} | Generated by JanMitra AI Eligibility Assistant'
        self.cell(0, 10, footer_text, 0, 0, 'C')


def generate_eligibility_pdf(filename: str, profile: Dict[str, Any], results: Dict[str, Any], language: str = "English"):
    """
    Generates a structured, professional PDF report from the results map.
    """
    use_nirmala = False
    nirmala_path = r"C:\Windows\Fonts\Nirmala.ttf"
    nirmala_b_path = r"C:\Windows\Fonts\NirmalaB.ttf"
    if language == "Hindi" and os.path.exists(nirmala_path) and os.path.exists(nirmala_b_path):
        use_nirmala = True

    pdf = JanMitraPDFReport(use_nirmala=use_nirmala)
    pdf.alias_nb_pages()
    pdf.add_page()
    
    font_family = "Nirmala" if use_nirmala else "Helvetica"

    # 1. Personal Profile Section
    pdf.set_text_color(15, 118, 110) # Teal
    pdf.set_font(font_family, 'B', 14)
    sec1_title = '1. नागरिक प्रोफाइल सारांश' if use_nirmala else '1. Citizen Profile Summary'
    pdf.cell(0, 10, sec1_title, 0, 1, 'L')
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(5)
    
    pdf.set_text_color(0, 0, 0)
    
    profile_keys = {
        "full_name": "पूरा नाम" if use_nirmala else "Full Name",
        "age": "उम्र" if use_nirmala else "Age",
        "gender": "लिंग" if use_nirmala else "Gender",
        "state": "राज्य" if use_nirmala else "State",
        "occupation": "व्यवसाय" if use_nirmala else "Occupation",
        "income": "वार्षिक पारिवारिक आय" if use_nirmala else "Annual Family Income",
        "social_category": "सामाजिक श्रेणी" if use_nirmala else "Social Category",
        "landholder": "कृषि भूमि का स्वामित्व" if use_nirmala else "Owns Agricultural Land",
        "is_disabled": "शारीरिक विकलांगता" if use_nirmala else "Physical Disability"
    }
    
    # Render table-like key-value structure
    for key, label in profile_keys.items():
        val = profile.get(key)
        if val is None:
            val = "निर्दिष्ट नहीं" if use_nirmala else "Not Specified"
        elif isinstance(val, bool):
            if use_nirmala:
                val = "हाँ" if val else "नहीं"
            else:
                val = "Yes" if val else "No"
        elif key == "income" and isinstance(val, (int, float)):
            val = f"₹ {val:,.2f}" if use_nirmala else f"Rs. {val:,.2f}"
        elif key == "occupation" and use_nirmala:
            occ_map = {"Farmer": "किसान", "Student": "छात्र", "Business Owner": "व्यवसायी", "Unemployed": "बेरोजगार", "Salaried": "नौकरीपेशा"}
            val = occ_map.get(val, val)
        elif key == "gender" and use_nirmala:
            g_map = {"Male": "पुरुष", "Female": "महिला", "Other": "अन्य"}
            val = g_map.get(val, val)
        elif key == "state" and use_nirmala:
            from backend.app.utils.translator import translate_str
            val = translate_str(val)

        pdf.set_font(font_family, 'B', 10)
        pdf.cell(50, 6, f"{label}:", 0, 0)
        pdf.set_font(font_family, '', 10)
        pdf.cell(0, 6, str(val), 0, 1)
        
    pdf.ln(10)
    
    # 2. Eligible Schemes Section
    pdf.set_text_color(15, 118, 110)
    pdf.set_font(font_family, 'B', 14)
    sec2_title = '2. योग्य सरकारी योजनाएं' if use_nirmala else '2. Eligible Government Schemes'
    pdf.cell(0, 10, sec2_title, 0, 1, 'L')
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(5)
    
    eligibility_results = results.get("eligibility_results", {})
    eligible_schemes = (
        eligibility_results.get("Highly Eligible", []) + 
        eligibility_results.get("Eligible", []) + 
        eligibility_results.get("Potentially Eligible", [])
    )
    
    if not eligible_schemes:
        pdf.set_text_color(128, 0, 0)
        pdf.set_font(font_family, 'I' if not use_nirmala else '', 10)
        no_schemes_txt = 'वर्तमान प्रोफाइल मापदंडों के आधार पर कोई योग्य योजना नहीं मिली।' if use_nirmala else 'No eligible schemes found based on current profile parameters.'
        pdf.cell(0, 10, no_schemes_txt, 0, 1)
    else:
        for idx, scheme in enumerate(eligible_schemes, 1):
            pdf.set_text_color(15, 118, 110)
            pdf.set_font(font_family, 'B', 11)
            state_text = "केंद्र सरकार" if scheme.get("state") == "Central" or scheme.get("state") == "केंद्र" else f"{scheme.get('state')} सरकार"
            pdf.cell(0, 8, f"{idx}. {scheme['scheme_name']} ({state_text})", 0, 1)
            
            pdf.set_text_color(0, 0, 0)
            pdf.set_font(font_family, 'I' if not use_nirmala else '', 9)
            pdf.cell(0, 5, f"मंत्रालय: {scheme['ministry']}" if use_nirmala else f"Ministry: {scheme['ministry']}", 0, 1)
            
            pdf.set_font(font_family, 'B', 9)
            pdf.cell(40, 5, "पात्रता प्रतिशत:" if use_nirmala else "Match Percentage:", 0, 0)
            pdf.set_font(font_family, '', 9)
            
            # Map status
            status_text = scheme['status']
            if use_nirmala:
                status_map = {"Highly Eligible": "अत्यधिक पात्र", "Eligible": "पात्र", "Potentially Eligible": "संभावित रूप से पात्र", "Ineligible": "अपात्र"}
                status_text = status_map.get(status_text, status_text)
            pdf.cell(0, 5, f"{scheme['match_percentage']}% ({status_text})", 0, 1)
            
            pdf.set_font(font_family, 'B', 9)
            pdf.cell(40, 5, "मुख्य लाभ:" if use_nirmala else "Key Benefits:", 0, 1)
            pdf.set_font(font_family, '', 9)
            for benefit in scheme.get("benefits", []):
                pdf.multi_cell(0, 4, f"- {benefit}")
                
            pdf.set_font(font_family, 'B', 9)
            pdf.cell(40, 5, "आवेदन लिंक:" if use_nirmala else "Application Link:", 0, 0)
            pdf.set_font(font_family, '', 9)
            pdf.cell(0, 5, scheme.get("official_link", "N/A"), 0, 1)
            pdf.ln(3)

    pdf.ln(10)
    
    # 3. Document Gap Checklist
    pdf.set_text_color(15, 118, 110)
    pdf.set_font(font_family, 'B', 14)
    sec3_title = '3. दस्तावेज़ तैयारी चेकलिस्ट' if use_nirmala else '3. Document Readiness Checklist'
    pdf.cell(0, 10, sec3_title, 0, 1, 'L')
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(5)
    
    doc_analysis = results.get("document_analysis", {})
    pdf.set_text_color(0, 0, 0)
    pdf.set_font(font_family, 'B', 10)
    pdf.cell(50, 6, "कुल दस्तावेज़ तैयारी:" if use_nirmala else "Overall Document Readiness:", 0, 0)
    pdf.set_font(font_family, '', 10)
    pdf.cell(0, 6, f"{doc_analysis.get('readiness_score', 0)}%", 0, 1)
    
    pdf.ln(3)
    pdf.set_font(font_family, 'B', 10)
    pdf.cell(100, 6, "उपलब्ध दस्तावेज़:" if use_nirmala else "Available Documents:", 0, 0)
    pdf.cell(0, 6, "लापता दस्तावेज़:" if use_nirmala else "Missing Documents:", 0, 1)
    
    pdf.set_font(font_family, '', 9)
    available_docs_list = doc_analysis.get("available", [])
    missing_docs_list = doc_analysis.get("missing", [])
    
    max_len = max(len(available_docs_list), len(missing_docs_list))
    for i in range(max_len):
        av_txt = f"[y] {available_docs_list[i]}" if i < len(available_docs_list) else ""
        ms_txt = f"[x] {missing_docs_list[i]}" if i < len(missing_docs_list) else ""
        
        pdf.cell(100, 5, av_txt, 0, 0)
        pdf.cell(0, 5, ms_txt, 0, 1)
        
    pdf.ln(10)
    
    # 4. Action Plan Section
    pdf.set_text_color(15, 118, 110)
    pdf.set_font(font_family, 'B', 14)
    sec4_title = '4. व्यक्तिगत कार्य योजना' if use_nirmala else '4. Personalized Action Plan'
    pdf.cell(0, 10, sec4_title, 0, 1, 'L')
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(5)
    
    action_plan = results.get("action_plan", {})
    pdf.set_text_color(0, 0, 0)
    pdf.set_font(font_family, 'B', 10)
    pdf.cell(50, 6, "अनुमानित तैयारी समय:" if use_nirmala else "Estimated Prep Time:", 0, 0)
    pdf.set_font(font_family, '', 10)
    days_unit = "दिन" if use_nirmala else "Days"
    pdf.cell(0, 6, f"{action_plan.get('estimated_completion_days', 0)} {days_unit}", 0, 1)
    pdf.ln(3)
    
    for step in action_plan.get("steps", []):
        pdf.set_fill_color(240, 240, 240)
        pdf.set_font(font_family, 'B', 10)
        step_lbl = "चरण" if use_nirmala else "Step"
        est_lbl = "अनुमानित समय" if use_nirmala else "Est. Time"
        pdf.cell(0, 6, f"{step_lbl} {step['step_number']}: {step['title']} ({est_lbl}: {step['estimated_time']})", 0, 1, 'L', True)
        
        pdf.set_font(font_family, '', 9)
        pdf.multi_cell(0, 5, step['description'])
        
        pdf.set_font(font_family, 'B', 8)
        pdf.cell(0, 4, "आवश्यक कार्रवाई:" if use_nirmala else "Actions required:", 0, 1)
        pdf.set_font(font_family, '', 8.5)
        for act in step.get("actions", []):
            pdf.multi_cell(0, 4.5, f"-> {act}")
        pdf.ln(4)
        
    pdf.output(filename)
    return filename
